/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminSitesRouteImport } from './routes/admin.sites'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as EditorSiteIdRouteImport } from './routes/editor.$siteId'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel.configuracoes'
import { Route as PainelModelosRouteImport } from './routes/painel.modelos'
import { Route as PainelSitesRouteImport } from './routes/painel.sites'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const EditorSiteIdRoute = EditorSiteIdRouteImport.update({
  id: '/editor/$siteId',
  path: '/editor/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelModelosRoute = PainelModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelSitesRoute = PainelSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => PainelRoute,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/criar': typeof CriarRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof PainelRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/editor/$siteId': typeof EditorSiteIdRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/modelos': typeof PainelModelosRoute
  '/painel/sites': typeof PainelSitesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/criar': typeof CriarRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/editor/$siteId': typeof EditorSiteIdRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/modelos': typeof PainelModelosRoute
  '/painel/sites': typeof PainelSitesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/admin': typeof AdminIndexRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/criar': typeof CriarRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof PainelRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/editor/$siteId': typeof EditorSiteIdRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/modelos': typeof PainelModelosRoute
  '/painel/sites': typeof PainelSitesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/criar'
    | '/entrar'
    | '/painel'
    | '/recuperar-senha'
    | '/admin/relatorios'
    | '/admin/sites'
    | '/admin/usuarios'
    | '/editor/$siteId'
    | '/painel/configuracoes'
    | '/painel/modelos'
    | '/painel/sites'
    | '/site/$slug'
    | '/admin/'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/criar'
    | '/entrar'
    | '/recuperar-senha'
    | '/admin/relatorios'
    | '/admin/sites'
    | '/admin/usuarios'
    | '/editor/$siteId'
    | '/painel/configuracoes'
    | '/painel/modelos'
    | '/painel/sites'
    | '/site/$slug'
    | '/admin'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/criar'
    | '/entrar'
    | '/painel'
    | '/recuperar-senha'
    | '/admin/relatorios'
    | '/admin/sites'
    | '/admin/usuarios'
    | '/editor/$siteId'
    | '/painel/configuracoes'
    | '/painel/modelos'
    | '/painel/sites'
    | '/site/$slug'
    | '/admin/'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CriarRoute: typeof CriarRoute
  EntrarRoute: typeof EntrarRoute
  PainelRoute: typeof PainelRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  EditorSiteIdRoute: typeof EditorSiteIdRoute
  SiteSlugRoute: typeof SiteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sites': {
      id: '/admin/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/editor/$siteId': {
      id: '/editor/$siteId'
      path: '/editor/$siteId'
      fullPath: '/editor/$siteId'
      preLoaderRoute: typeof EditorSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/modelos': {
      id: '/painel/modelos'
      path: '/modelos'
      fullPath: '/painel/modelos'
      preLoaderRoute: typeof PainelModelosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/sites': {
      id: '/painel/sites'
      path: '/sites'
      fullPath: '/painel/sites'
      preLoaderRoute: typeof PainelSitesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSitesRoute: typeof AdminSitesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSitesRoute: AdminSitesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PainelRouteChildren {
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelModelosRoute: typeof PainelModelosRoute
  PainelSitesRoute: typeof PainelSitesRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelModelosRoute: PainelModelosRoute,
  PainelSitesRoute: PainelSitesRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CriarRoute: CriarRoute,
  EntrarRoute: EntrarRoute,
  PainelRoute: PainelRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  EditorSiteIdRoute: EditorSiteIdRoute,
  SiteSlugRoute: SiteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
